
# properties 면 더 귀찮게 적음
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    check-template-location: true
    prefix: classpath:templates/
    #    resources
    suffix: .html
    mode: HTML
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3308/bknk
    username: root
    password: koreait
    driver-class-name: org.mariadb.jdbc.Driver
  #    url를 보고 설정해주기 때문에 안줘도 상관은 없을것이다 랬는데 안된다
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 30MB
      location: D:\springImg2
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:  # 보안 비밀
            scope:
              - profile
              - email
          facebook:
            client-id:  # bknk - Test1
            client-secret:
            scope:
              - email
              - public_profile
          kakao:
            authorization-grant-type: authorization_code
            client-id:  #카카오 요약정보에 REST API키
            client-secret:  #카카오 로그인의 보안에서 client secret
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}" #{baseUrl}:localhost {registrationId}:kakao
            scope:
              - profile_nickname
              - profile_image
#              - account_email
#              - gender
            client-authentication-method: POST
            client-name: Kakao
          naver:
            authorization-grant-type: authorization_code
            client-id:  #네이버 Client-id
            client-secret:  #네이버 client-secret
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}" #{registrationId}:naver
            scope: name,profile_image # ,gender,mobile,email
            client-name: Naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: properties
            # JSON 형태에서 "properties"라는 key값에 해당하는 value에 회원 정보가 담겨져있다.
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
            # JSON 형태에서 "response"라는 key값에 해당하는 value에 회원 정보가 담겨져있다.
mybatis:
  mapper-locations: mybatis-mapper/**/*.xml
  type-aliases-package: com.koreait.bknk
  # 덕분에 편하게적는다 mapper에?

# 톰켓 포트 변경
server:
  port: 8090
#  기본적으로 80으로 날아감